"""MongoDB-backed stores: login/users, per-enterprise profile facts
(loan principal, sector, village — seeded once from the ML pipeline's
enterprises.csv), and app-entered ledger transactions. The ML-generated
historical ledger/scores/forecasts CSVs (app/store.py) stay CSV-backed —
they're regenerated by the batch scorer, not user-originated state.
Alerts, interventions, and AI-chat history still live in SQLite."""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime

from bson import ObjectId
from pymongo import MongoClient
from pymongo.collection import Collection

from .config import settings

_client: MongoClient | None = None


def get_client() -> MongoClient:
    global _client
    if _client is None:
        _client = MongoClient(settings.MONGODB_URI)
    return _client


def users_collection() -> Collection:
    return get_client()[settings.MONGODB_DB_NAME]["users"]


def enterprise_profiles_collection() -> Collection:
    return get_client()[settings.MONGODB_DB_NAME]["enterprise_profiles"]


def ledger_entries_collection() -> Collection:
    return get_client()[settings.MONGODB_DB_NAME]["ledger_entries"]


def direct_messages_collection() -> Collection:
    return get_client()[settings.MONGODB_DB_NAME]["direct_messages"]


def ensure_indexes() -> None:
    users_collection().create_index("username", unique=True)
    users_collection().create_index("id", unique=True)
    enterprise_profiles_collection().create_index("id", unique=True)
    ledger_entries_collection().create_index("enterprise_id")
    ledger_entries_collection().create_index("client_uuid", unique=True, sparse=True)
    direct_messages_collection().create_index([("enterprise_id", 1), ("created_at", 1)])


@dataclass
class User:
    """Mirrors the shape of the old SQLAlchemy User model so existing
    routers (which only type-annotate `user: User` from Depends) don't
    need to change."""
    id: int
    username: str
    password_hash: str
    role: str  # 'officer' | 'enterprise'
    enterprise_id: int | None
    display_name: str = ""


def _to_user(doc: dict | None) -> User | None:
    if doc is None:
        return None
    return User(
        id=doc["id"],
        username=doc["username"],
        password_hash=doc["password_hash"],
        role=doc["role"],
        enterprise_id=doc.get("enterprise_id"),
        display_name=doc.get("display_name", ""),
    )


def find_user_by_username(username: str) -> User | None:
    return _to_user(users_collection().find_one({"username": username}))


def find_user_by_id(user_id: int) -> User | None:
    return _to_user(users_collection().find_one({"id": user_id}))


def find_users_by_role(role: str) -> list[User]:
    return [_to_user(d) for d in users_collection().find({"role": role})]


def find_users_by_enterprise_ids(enterprise_ids: list[int]) -> list[User]:
    return [_to_user(d) for d in users_collection().find({"enterprise_id": {"$in": enterprise_ids}})]


def insert_user(user: User) -> None:
    doc = {
        "id": user.id,
        "username": user.username,
        "password_hash": user.password_hash,
        "role": user.role,
        "enterprise_id": user.enterprise_id,
        "display_name": user.display_name,
    }
    users_collection().insert_one(doc)


def count_users() -> int:
    return users_collection().count_documents({})


# --------------------------------------------------------- enterprise profiles
def find_enterprise_profile(eid: int) -> dict | None:
    doc = enterprise_profiles_collection().find_one({"id": eid}, {"_id": 0})
    return doc


def insert_enterprise_profile(doc: dict) -> None:
    enterprise_profiles_collection().insert_one(dict(doc))


def count_enterprise_profiles() -> int:
    return enterprise_profiles_collection().count_documents({})


# -------------------------------------------------------------- ledger entries
def find_ledger_entries_by_enterprise(eid: int) -> list[dict]:
    return list(ledger_entries_collection().find({"enterprise_id": eid}))


def find_ledger_entry_by_client_uuid(client_uuid: str) -> dict | None:
    return ledger_entries_collection().find_one({"client_uuid": client_uuid})


def insert_ledger_entry(*, enterprise_id: int, date: str, kind: str, category: str,
                        amount: float, note: str, client_uuid: str | None) -> dict:
    doc = {
        "enterprise_id": enterprise_id, "date": date,
        "kind": kind, "category": category, "amount": amount, "note": note,
        "created_at": datetime.utcnow(),
    }
    # the client_uuid index is sparse (unique only among documents where the
    # field is present) — omit the key entirely rather than storing `None`,
    # or every entry without a client_uuid would collide on a shared null.
    if client_uuid:
        doc["client_uuid"] = client_uuid
    result = ledger_entries_collection().insert_one(doc)
    doc["_id"] = result.inserted_id
    doc.setdefault("client_uuid", None)
    return doc


def ledger_entry_id(doc: dict) -> str:
    oid: ObjectId = doc["_id"]
    return str(oid)


# ------------------------------------------------------------- direct messages
def find_messages_by_enterprise(eid: int) -> list[dict]:
    return list(direct_messages_collection().find({"enterprise_id": eid}).sort("created_at", 1))


def find_all_messages() -> list[dict]:
    """Every message, oldest first — used to build the officer's thread list."""
    return list(direct_messages_collection().find().sort("created_at", 1))


def insert_direct_message(*, enterprise_id: int, sender_role: str, sender_name: str,
                          content: str) -> dict:
    doc = {
        "enterprise_id": enterprise_id, "sender_role": sender_role,
        "sender_name": sender_name, "content": content,
        "read_by_officer": sender_role == "officer",
        "read_by_enterprise": sender_role == "enterprise",
        "created_at": datetime.utcnow(),
    }
    result = direct_messages_collection().insert_one(doc)
    doc["_id"] = result.inserted_id
    return doc


def mark_thread_read(eid: int, reader_role: str) -> None:
    other = "enterprise" if reader_role == "officer" else "officer"
    read_field = "read_by_officer" if reader_role == "officer" else "read_by_enterprise"
    direct_messages_collection().update_many(
        {"enterprise_id": eid, "sender_role": other, read_field: False},
        {"$set": {read_field: True}})


def count_messages_since(eid: int, sender_role: str, since: datetime) -> int:
    return direct_messages_collection().count_documents({
        "enterprise_id": eid, "sender_role": sender_role, "created_at": {"$gte": since},
    })


def unread_counts_for(role: str, enterprise_id: int | None = None) -> dict[int, int]:
    other = "enterprise" if role == "officer" else "officer"
    read_field = "read_by_officer" if role == "officer" else "read_by_enterprise"
    match: dict = {"sender_role": other, read_field: False}
    if enterprise_id is not None:
        match["enterprise_id"] = enterprise_id
    pipeline = [{"$match": match}, {"$group": {"_id": "$enterprise_id", "n": {"$sum": 1}}}]
    return {int(r["_id"]): int(r["n"]) for r in direct_messages_collection().aggregate(pipeline)}


def message_id(doc: dict) -> str:
    oid: ObjectId = doc["_id"]
    return str(oid)
